### ISSUE TITLE
DO NOT UPDATE THE FLATPAK

### ISSUE THREAD

**Issue by orowith2os** [flathub/org.polymc.PolyMC#35] opened 2022-10-17 19:45 UTC
PolyMC seems to have been compromised, as of commit https://github.com/PolyMC/PolyMC/commit/ccf282593dcdbe189c99b81b8bc90cb203aed3ee

Do NOT update this flatpak until the issue has been resolved, and upstream can be sure that it's safe.

**Comment by orowith2os** [comment] 2022-10-17 20:14
The developers seem to have made a fork here, this flatpak should be updated when needed to use this: https://github.com/PlaceholderMC/PlaceholderMC

**Comment by dada513** [comment] 2022-10-17 20:27
Once we get the metaserver running under our controls, I will update this to the PlaceholderMC version

**Comment by tim77** [comment] 2022-10-17 22:02
https://twitter.com/gamingonlinux/status/1582103691762405378

**Comment by AndrejSh3** [comment] 2022-10-18 07:00
Until then, would it be possible to replace the flatpak manifest with a blank window that's warning users to disconnect their account from polymc? Might be a great way to reach a lot of users who might be unaware of the situation.

**Comment by OpenBagTwo** [comment] 2022-10-18 08:55
> warning users to disconnect their account from polymc?

I've seen reports on both Twitter and reddit that PolyMC's MSA access has been revoked. IIRC @Scrumplex said he controlled the MSA auths, so my guess is he deleted it?

In any case, sounds like the "disconnect your account" part is unnecessary. I'd love for a PrismLauncher dev to weigh in, but it sounds like the only risk at this point comes from fetching data from the PolyMC meta server, and I'm not sure what safeguards are already in place to prevent malicious behavior there (e.g. hard-coded checksums to ensure that the LWJGL version you're downloading is actually LWJGL?)

**Comment by Scrumplex** [comment] 2022-10-18 08:56
I deleted the MSA application, yes. Authentication was done purely between the client and Microsoft servers, so existing accounts should be safe.

**Comment by greanthai420** [comment] 2022-10-18 09:10
Stop spamming and spreading misinformation.
Poly is not compromised. Everybody can take a look at the source.

You're just spreading the misinformation because hatred clouds your judgement.

May Allah guide you.

**Comment by admiralnelson** [comment] 2022-10-18 10:17
The repo is fine, there's no malicious code there.

**Comment by iamcult** [comment] 2022-10-18 10:42
The problem is not that there is currently malicious code in the repo, the problem is that the keyholder to the repository has gone rogue, and you would probably not do well to continue trusting the repo at all. To quote a comment on the original commit thread (https://github.com/PolyMC/PolyMC/commit/ccf282593dcdbe189c99b81b8bc90cb203aed3ee#commitcomment-87074543):
> One of the contributors locked out the other ones because they wanted to add a bog standard code of conduct for contributors to sign before submitting code like most open source projects do, and he said he hates "queer ideology" which I think is twitter speak for gay people.

**Comment by LennyMcLennington** [comment] 2022-10-18 13:06
I don't know why you people think I would do something highly illegal or have any motivation to do so, let alone on a project where all the code and meta data are publicly auditable. This repo should not be changed to use your fork, you should request a new one to be made.

**Comment by Scrumplex** [comment] 2022-10-18 13:08
@LennyMcLennington Can you fix your Translations repo? I get regular emails of failing actions, because I was the last committer.

**Comment by SViN24** [comment] 2022-10-18 14:48
I have to respectfully disagree with the decision to hard move users to a new package or specifically stop updating this package.
Yes i know the application takeover was weird and certainly unprofessional but i do not think that in the end of the day its flathub's job to dictate if users get to use a specific package from a specific dev.

Obviously i do not mind if the other people in the team decide to hard fork the project and make another flatpak for PrismMC.

I am also not a Flathub/Flatpak dev but this is just my opinion that i hope repo owners consider.

A few extra points:

* Yes there was a takeover of the application but so far there has been no real indication that it will provide malware or hack the users. That assumption is made without proof. Now am I not in the project chatgroup nor do i care to be.
* Ultimately this does not matter to Flathub. Flathub hosts packages whose original devs many find repulsive(mozilla/brave for example) or actively do things many in the opensource community find bad(microsoft/google and its packages), or environmental groups may find bad(all the crypto wallet apps), singling out a package for what i can best describe community drama is at best unprofessional and at worst against a misapplication of rules.
* Projects have drama behind them, this is true and universal. Heck everyone in the linux community knows this since it seems like we can't even go a week without some kind of mess happening.

To the current and single PolyMC dev @LennyMcLennington:

This entire situation could have been handled better. 
You could have just left the project and started a hard fork of some kind with different rules for moderation or you could have just argued for different rules for moderation with your team.
It frankly aches me to see this kind of unprofessionalism and pretty twitter-tier slap fighting happen.

I am aware that PolyMC has a newsreader feature. I think it would be best to inform your userbase that at least a project split has happened.

**Comment by admiralnelson** [comment] 2022-10-18 14:50
I’m sorry, I think plain accusation will get us nowhere. I don’t think his intent will install malware like you said.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Scrumplex** [comment] 2022-10-18 14:54
> I have to respectfully disagree with the decision to hard move users to a new package or specifically stop updating this package.

Point is: @LennyMcLennington is not maintaining this Flatpak. He barely maintains PolyMC itself.
We certainly won't maintain this Flatpak any further and decomission it as per [Flathub guidelines](https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life)

**Comment by SViN24** [comment] 2022-10-18 15:20
> > I have to respectfully disagree with the decision to hard move users to a new package or specifically stop updating this package.
> 
> Point is: @LennyMcLennington is not maintaining this Flatpak. He barely maintains PolyMC itself. We certainly won't maintain this Flatpak any further and decomission it as per [Flathub guidelines](https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life)

then i would recommend marking it as EOL and adding a notice if no one is willing to pick it up.(And if lenny can't find devs to help him maintain polyMC).
i would argue letting the users moving to prismMC as they wish.

**Comment by KaspianDev** [comment] 2022-10-18 16:30
Imo this flatpak should be left untouched.
The project is not dead as far as I'm concerned, original author is still interested in continuing it.
Also there's no hijacking and safety checks should be the same as for any other project, maintainer should make sure no bad code is in the flatpak.

**Comment by Scrumplex** [comment] 2022-10-18 16:41
@KaspianDev why should the maintainer of this Flatpak continue maintaining this package, if they have already moved on to a new launcher.

If someone else wants to maintain it, sure go ahead. But we will decomission this package

**Comment by KaspianDev** [comment] 2022-10-18 16:51
I'd let  Lenny decide if he wants to update it or not, otherwise you could decommission it.
Ofc it's not in your interest now to maintain this, i truly understand.

PS: Do you know where I can find new poly fork discord server? I've heard you get attacks idk if it's possible to join rn lmk.

**Comment by Scrumplex** [comment] 2022-10-18 17:55
> PS: Do you know where I can find new poly fork discord server? I've heard you get attacks idk if it's possible to join rn lmk.

https://prismlauncher.org/discord

**Comment by SViN24** [comment] 2022-10-18 19:56
> In my opinion we should treat PrizmMC as the original project, forced to rename, and "PolyMC" (which is not really PolyMC any more) as the fork. PrizmMC is made by the original PolyMC team (minus one person who didn't contribute much anyway) with the same goals, and is the true PolyMC, and "PolyMC" is now a rouge and hostile fork that happens to have control over the original repo and Discord server, and has taken over the name.

While I can understand your sentiment, consider the following:
As of now it seems like both projects exist and the polymc namespace is taken by polymc. 
I don't know how to explain this but the idea of hard migrating all users of a program doesn't sit well with me. 
I don't think we get to choose what they install on their system.

**Comment by binex-dsk** [comment] 2022-10-18 23:06
I can maintain  this

**Comment by orowith2os** [comment] 2022-10-19 13:11
I think it's safe to assume that this package will be EOLed in favor of a PrismLauncher flatpak, and for good reason.

Lenny took over PolyMC and destroyed the trust of everybody using PolyMC, and not he nor any people related to him (that includes you, @binex-dsk) are fit to maintain a package that people will use. Lenny alone isn't even maintaining the PolyMC repo at this point, just doing *not even* the bare minimum.

I think we can all be in agreement with this. (those that have a say in this, at least)

and to you, @LennyMcLennington: trans rights :transgender_flag: :transgender_flag: :transgender_flag:

**Comment by Littlemac123** [comment] 2022-11-02 16:49
i think Lenny should be able to keep the flatpak of polyMC, I think hes trustworthy. all he wanted was to remove the code of conduct that the other devs wanted to force in there.

**Comment by SViN24** [comment] 2022-11-02 19:43
lenny can discuss things with the flathub repo owners
If they dont want to give him control of the package he can set up his own  flatpak repo

**Comment by noelelias** [comment] 2022-11-12 20:28
Members of GitHub/PolyMC/PolyMC are @BowDown098 @HeyaGlitz @LennyMcLennington @Sneedplex

and according to the contribution guide it's absolutely clear:

> We would prefer that these applications are controlled by their authors.
> 
> If an application that belongs to you is being distributed without your involvement, please get in touch with the Flathub admins, so that we can discuss transfering ownership.

Since the original owner of this repo is no longer using it how flathub prefers it to be done, one of the members mentioned above have to get in touch with the Flathub admins to transfer the ownership.

**Comment by HeyaGlitz** [comment] 2022-11-12 20:36
https://github.com/flathub/flathub/issues/3600
It's not like we haven't tried already

**Closed** 2022-11-13 20:10 UTC

**Comment by xAffan** [comment] 2023-05-21 11:04
> > PS: Do you know where I can find new poly fork discord server? I've heard you get attacks idk if it's possible to join rn lmk.
> 
> https://discord.gg/prismlauncher

Why are you promoting your fork here? This is not a thread to discuss your fork, or your ideology.

**Comment by KaspianDev** [comment] 2023-05-21 20:19
> > https://discord.gg/prismlauncher
> 
> Why are you promoting your fork here? This is not a thread to discuss your fork, or your ideology.

![chad](https://github.com/flathub/org.polymc.PolyMC/assets/34658474/74c5a0b0-979e-4f52-98a5-c82a171111bd)

> > PS: Do you know where I can find new poly fork discord server? I've heard you get attacks idk if it's possible to join rn lmk.
> 
> https://discord.gg/prismlauncher

![jak](https://github.com/flathub/org.polymc.PolyMC/assets/34658474/8d7f8865-d124-4364-8985-51a9b1fe1681)

**Comment by CommanderTaboo** [comment] 2023-05-21 20:45
the true link the the official poly mc discord server is >>>> https://discord.gg/WMtwnF5Cbr
![poly mc discord server](https://github.com/flathub/org.polymc.PolyMC/assets/60798074/46189599-3bf8-4934-841c-c1dd87bb7bd8)

**Comment by lockjock** [comment] 2023-05-21 20:49
Prism is not any better then Poly, and in fact it's much worse. All Prism brings to the table is a very political and sexuality focused community and a somehow very unstable launcher. It's riddled with bugs and has out of this world memory leaks. Take a look on their discord support and Github issue and you have all the proof you need about it's instability. It's embarrassing. Furthermore, all this political and sexuality garbage should have no business near any game or game launcher, especially something that's mainly played by children. I find it unmoral and wrong to push such ideologies in software that has absolutely nothing to do with it. There is no "malicious code" or any sort of thing of that nature, you people are simply spreading misinformation. Lenny didn't go rouge, he was simply tired of you crazy people forcing crazy ideologies in his code. It sad to see the software community fight about stuff that has absolutely nothing to do with software in general.
